# Generated by Django 5.1.4 on 2025-05-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_aboutusfounder_aboutusimages_aboutusimagetitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusourvision',
            name='our_vision',
            field=models.CharField(max_length=1000),
        ),
    ]
