# Generated by Django 5.1.4 on 2025-05-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0005_alter_aboutusourvision_our_vision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusourpolicy',
            name='description',
        ),
        migrations.AlterField(
            model_name='aboutusourpolicy',
            name='our_policy',
            field=models.CharField(max_length=1000),
        ),
    ]
