# Generated by Django 5.1.4 on 2025-05-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0006_remove_aboutusourpolicy_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusourpolicybox',
            name='our_policy_box',
            field=models.CharField(max_length=1000),
        ),
    ]
