# Generated by Django 5.1.4 on 2025-05-01 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0007_alter_aboutusourpolicybox_our_policy_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabitem',
            name='title',
        ),
    ]
