# Generated by Django 5.1.4 on 2025-05-01 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0008_remove_tabitem_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyitem',
            name='icon_class',
        ),
    ]
