# Generated by Django 5.1.4 on 2025-05-01 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0009_remove_historyitem_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyitem',
            name='section',
        ),
        migrations.DeleteModel(
            name='HistorySection',
        ),
    ]
