# Generated by Django 5.1.4 on 2025-05-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0010_remove_historyitem_section_delete_historysection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourteam',
            name='image_url',
        ),
        migrations.AddField(
            model_name='ourteam',
            name='image',
            field=models.ImageField(default='team_images/default.jpg', upload_to='team_images/'),
        ),
    ]
