# Generated by Django 5.1.4 on 2025-05-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselslide',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='carousel/videos/'),
        ),
    ]
