# Generated by Django 5.1.4 on 2025-05-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_carouselslide_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeDoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeDoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='What we do?', max_length=255)),
                ('paragraph', models.TextField()),
            ],
        ),
    ]
