# Generated by Django 5.1.4 on 2025-05-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_categoryhighlightsection_categoryhighlightbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueHighlightSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('first_image', models.ImageField(upload_to='catalogue_highlight/')),
                ('second_image', models.ImageField(upload_to='catalogue_highlight/')),
                ('button_text', models.CharField(default='See more', max_length=50)),
                ('button_url', models.URLField(blank=True)),
            ],
        ),
    ]
