# Generated by Django 5.1.4 on 2025-05-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_cataloguehighlightsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cataloguehighlightsection',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='cataloguehighlightsection',
            name='button_url',
        ),
    ]
