# Generated by Django 5.1.4 on 2025-05-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_cataloguehighlightsection_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FifthSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headtitle', models.CharField(max_length=255)),
                ('title_left', models.CharField(max_length=255)),
                ('subtitle_left', models.CharField(blank=True, max_length=255)),
                ('description_left', models.TextField()),
                ('icon_left', models.ImageField(upload_to='catalogue_icons/')),
                ('title_right', models.CharField(max_length=255)),
                ('subtitle_right', models.CharField(blank=True, max_length=255)),
                ('description_right', models.TextField()),
                ('icon_right', models.ImageField(upload_to='catalogue_icons/')),
            ],
        ),
    ]
