# Generated by Django 5.1.4 on 2025-05-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_fifthsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SixthSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=255)),
                ('title1', models.CharField(max_length=255)),
                ('description1', models.TextField()),
                ('image1', models.ImageField(upload_to='sixth_section/')),
                ('title2', models.CharField(max_length=255)),
                ('description2', models.TextField()),
                ('image2', models.ImageField(upload_to='sixth_section/')),
                ('title3', models.CharField(max_length=255)),
                ('description3', models.TextField()),
                ('image3', models.ImageField(upload_to='sixth_section/')),
                ('title4', models.CharField(max_length=255)),
                ('description4', models.TextField()),
                ('image4', models.ImageField(upload_to='sixth_section/')),
                ('title5', models.CharField(max_length=255)),
                ('description5', models.TextField()),
                ('image5', models.ImageField(upload_to='sixth_section/')),
            ],
        ),
    ]
