# Generated by Django 5.1.4 on 2025-05-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_sixthsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeventhSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.CharField(max_length=255)),
                ('button_text', models.CharField(max_length=100)),
                ('button_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
