# Generated by Django 5.1.4 on 2025-05-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_seventhsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seventhsection',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
