# Generated by Django 5.1.4 on 2025-05-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_seventhsection_button_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='EighthSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.TextField()),
                ('left_title', models.CharField(max_length=100)),
                ('left_content', models.TextField()),
                ('left_image', models.ImageField(blank=True, null=True, upload_to='eighthsection/left/')),
                ('right_first_title', models.CharField(max_length=100)),
                ('right_first_content', models.TextField()),
                ('right_first_image', models.ImageField(blank=True, null=True, upload_to='eighthsection/right_first/')),
                ('right_second_title', models.CharField(max_length=100)),
                ('right_second_content', models.TextField()),
                ('right_second_image', models.ImageField(blank=True, null=True, upload_to='eighthsection/right_second/')),
            ],
        ),
    ]
