# Generated by Django 5.1.4 on 2025-02-17 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('accepted_languages', models.CharField(blank=True, max_length=255, null=True)),
                ('floor_space', models.FloatField(blank=True, null=True)),
                ('years_exporting', models.IntegerField(blank=True, null=True)),
                ('annual_export_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('years_in_industry', models.IntegerField(blank=True, null=True)),
                ('production_lines', models.IntegerField(blank=True, null=True)),
                ('production_machines', models.IntegerField(blank=True, null=True)),
                ('product_support_traceability', models.BooleanField(blank=True, null=True)),
                ('product_inspection_method', models.TextField(blank=True, null=True)),
                ('quality_control_on_lines', models.BooleanField(blank=True, null=True)),
                ('qa_qc_inspectors', models.IntegerField(blank=True, null=True)),
                ('main_markets', models.TextField(blank=True, null=True)),
                ('supply_chain_partners', models.TextField(blank=True, null=True)),
                ('main_client_types', models.TextField(blank=True, null=True)),
                ('customization_options', models.TextField(blank=True, null=True)),
                ('new_products_last_year', models.IntegerField(blank=True, null=True)),
                ('rd_engineer_education_levels', models.CharField(blank=True, max_length=255, null=True)),
                ('rd_engineers', models.IntegerField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('other_social_media', models.JSONField(blank=True, null=True)),
                ('export_manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('responsible_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_fax', models.CharField(blank=True, max_length=20, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_location', models.CharField(blank=True, max_length=255, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('is_in_catalogue', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_entries', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_title', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('origin', models.CharField(blank=True, max_length=255, null=True)),
                ('availability', models.CharField(blank=True, choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], max_length=20, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image_title', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='companies.product')),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
