# Generated by Django 5.1.4 on 2025-02-18 00:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='company',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='catalogue',
            name='SellerProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellerprofilecatalogue', to='companies.sellerprofile'),
        ),
        migrations.AddField(
            model_name='certification',
            name='SellerProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellerprofileCertifications', to='companies.sellerprofile'),
        ),
        migrations.AddField(
            model_name='product',
            name='SellerProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.sellerprofile'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='accepted_languages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='accepted_terms',
            field=models.BooleanField(default=False, help_text='Indicates if the user has accepted the terms and conditions.'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='address',
            field=models.CharField(default='No address provided', max_length=255),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='annual_export_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='uploads/bank_statements/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='uploads/certificates/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='company_description',
            field=models.TextField(default='company_description'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='company_fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='company_license',
            field=models.FileField(default='uploads/company_licenses/default_license.pdf', upload_to='uploads/company_licenses/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='company_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='company_size',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='contact_email',
            field=models.EmailField(default='contact@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='country',
            field=models.CharField(default='Oman', max_length=255),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='customization_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='email_address',
            field=models.EmailField(default='No address provided', max_length=254),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='export_manager_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='fields_of_work',
            field=models.CharField(choices=[('technology', 'Technology'), ('consulting', 'Consulting'), ('manufacturing', 'Manufacturing'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('finance', 'Finance'), ('agriculture', 'Agriculture'), ('automotive', 'Automotive'), ('construction', 'Construction'), ('real-estate', 'Real Estate'), ('retail', 'Retail'), ('hospitality', 'Hospitality'), ('entertainment', 'Entertainment'), ('logistics', 'Logistics'), ('transportation', 'Transportation'), ('energy', 'Energy'), ('environmental-services', 'Environmental Services'), ('telecommunications', 'Telecommunications'), ('food-and-beverage', 'Food and Beverage'), ('pharmaceuticals', 'Pharmaceuticals'), ('media', 'Media'), ('arts-and-culture', 'Arts and Culture'), ('sports', 'Sports'), ('legal-services', 'Legal Services'), ('nonprofit', 'Nonprofit'), ('government', 'Government'), ('mining', 'Mining'), ('aerospace', 'Aerospace'), ('defense', 'Defense'), ('fashion', 'Fashion'), ('beauty-and-cosmetics', 'Beauty and Cosmetics'), ('cleaning-services', 'Cleaning Services'), ('technology-services', 'Technology Services'), ('cybersecurity', 'Cybersecurity'), ('blockchain-and-cryptocurrency', 'Blockchain and Cryptocurrency'), ('e-commerce', 'E-Commerce'), ('venture-capital', 'Venture Capital'), ('insurance', 'Insurance'), ('event-management', 'Event Management'), ('travel-and-tourism', 'Travel and Tourism'), ('petroleum', 'Petroleum'), ('biotechnology', 'Biotechnology'), ('research-and-development', 'Research and Development'), ('engineering', 'Engineering'), ('human-resources', 'Human Resources'), ('business-services', 'Business Services'), ('printing-and-publishing', 'Printing and Publishing'), ('handicrafts', 'Handicrafts'), ('marine-industry', 'Marine Industry'), ('architecture', 'Architecture'), ('interior-design', 'Interior Design'), ('artificial-intelligence', 'Artificial Intelligence'), ('robotics', 'Robotics'), ('gaming', 'Gaming'), ('fitness-and-wellness', 'Fitness and Wellness'), ('personal-care', 'Personal Care'), ('luxury-goods', 'Luxury Goods'), ('forestry', 'Forestry'), ('security-services', 'Security Services'), ('aviation', 'Aviation'), ('childcare', 'Childcare'), ('translation-services', 'Translation Services'), ('antiques-and-collectibles', 'Antiques and Collectibles'), ('recycling', 'Recycling'), ('marine-tourism', 'Marine Tourism')], default='technology', max_length=255),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='floor_space',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='full_name',
            field=models.CharField(default='John Doe', max_length=255),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='uploads/id_cards/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_in_catalogue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='main_client_types',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='main_markets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='new_products_last_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='other_social_media',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='uploads/passports/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='phone_number',
            field=models.CharField(default='+968 2020 2020', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='product_inspection_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='product_support_traceability',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='production_lines',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='production_machines',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='qa_qc_inspectors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='quality_control_on_lines',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='rd_engineer_education_levels',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='rd_engineers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='responsible_person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='supply_chain_partners',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='tax_registration',
            field=models.FileField(blank=True, null=True, upload_to='uploads/tax_registration/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='utility_bill',
            field=models.FileField(blank=True, null=True, upload_to='uploads/utility_bills/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='website_url',
            field=models.URLField(default='www.example.com'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='year_established',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='years_exporting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='years_in_industry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sellerprofilecertifications/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='company_address',
            field=models.TextField(default='No address provided'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='company_name',
            field=models.CharField(default='Sohof', max_length=255),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_title', models.CharField(blank=True, max_length=255, null=True)),
                ('SellerProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellerprofileVideos', to='companies.sellerprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyVideo',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
