# Generated by Django 5.1.4 on 2025-02-19 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_user_remove_catalogue_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CataloguePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_image', models.ImageField(blank=True, null=True, upload_to='catalogue_pages/')),
                ('page_name', models.CharField(blank=True, max_length=255, null=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='companies.catalogue')),
                ('sellers', models.ManyToManyField(related_name='catalogue_pages', to='companies.sellerprofile')),
            ],
        ),
    ]
