# Generated by Django 5.1.4 on 2025-02-19 07:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_cataloguepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cataloguepage',
            name='page_name',
        ),
        migrations.AddField(
            model_name='catalogue',
            name='companies',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='creator',
            field=models.CharField(default='Sohof', max_length=255),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='pages',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cataloguepage',
            name='page_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cataloguepage',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_pages', to='companies.catalogue'),
        ),
    ]
