# Generated by Django 5.1.4 on 2025-02-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_cataloguepage_page_name_catalogue_companies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='catalogues/covers/'),
        ),
    ]
