# Generated by Django 5.1.4 on 2025-02-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_catalogue_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
