# Generated by Django 5.1.4 on 2025-02-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_video_video_url_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='product image', upload_to='product_images/'),
        ),
    ]
