# Generated by Django 5.1.4 on 2025-02-20 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='SellerProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellerprofilecatalogue', to='companies.sellerprofile'),
        ),
    ]
