# Generated by Django 5.1.4 on 2025-02-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_catalogue_sellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='detail_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_gold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='profile_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
