# Generated by Django 5.1.4 on 2025-02-20 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_sellerprofile_detail_views_sellerprofile_is_gold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='detail_views',
        ),
    ]
