# Generated by Django 5.1.4 on 2025-02-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_category_product_category_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
