# Generated by Django 5.1.4 on 2025-02-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_product_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='icon',
            field=models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-pagelines')", max_length=255, null=True),
        ),
    ]
