# Generated by Django 5.1.4 on 2025-02-24 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_profileview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileView',
        ),
    ]
