# Generated by Django 5.1.4 on 2025-02-24 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_delete_profileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='daily_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='weekly_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProfileViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='companies.sellerprofile')),
            ],
        ),
    ]
