# Generated by Django 5.1.4 on 2025-03-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_sellerprofile_daily_views_sellerprofile_weekly_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='daily_views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='profile_views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='weekly_views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
