# Generated by Django 5.1.4 on 2025-04-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_alter_sellerprofile_daily_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='title',
            field=models.CharField(blank=True, default='Catalogue Title', max_length=255, null=True),
        ),
    ]
