# Generated by Django 5.1.4 on 2025-04-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_catalogue_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='description',
            field=models.CharField(blank=True, default='Catalogue Description', max_length=1000, null=True),
        ),
    ]
