# Generated by Django 5.1.4 on 2025-05-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_catalogue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='catalogues/pdfs/'),
        ),
    ]
