# Generated by Django 5.1.4 on 2025-05-01 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_catalogue_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='pdf_file',
        ),
    ]
