# Generated by Django 5.1.4 on 2025-05-01 04:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_pdfdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cataloguepage',
            name='catalogue',
        ),
        migrations.RemoveField(
            model_name='pdfdocument',
            name='name',
        ),
        migrations.AddField(
            model_name='cataloguepage',
            name='pdf_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_pages', to='companies.pdfdocument'),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='SellerProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellerprofilecatalogue', to='companies.sellerprofile'),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='added_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='companies',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='catalogues/covers/'),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='creator',
            field=models.CharField(default='Sohof', max_length=255),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='description',
            field=models.CharField(blank=True, default='Catalogue Description', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='pages',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='title',
            field=models.CharField(blank=True, default='Catalogue Title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Catalogue',
        ),
    ]
