# Generated by Django 5.1.4 on 2025-05-01 04:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_remove_cataloguepage_catalogue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cataloguepage',
            name='pdf_document',
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField(auto_now_add=True)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('creator', models.CharField(default='Sohof', max_length=255)),
                ('language', models.CharField(default='English', max_length=50)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('pages', models.PositiveIntegerField(default=50)),
                ('companies', models.PositiveIntegerField(default=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='catalogues/covers/')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, default='Catalogue Title', max_length=255, null=True)),
                ('description', models.CharField(blank=True, default='Catalogue Description', max_length=1000, null=True)),
                ('SellerProfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellerprofilecatalogue', to='companies.sellerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='cataloguepage',
            name='catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_pages', to='companies.catalogue'),
        ),
        migrations.DeleteModel(
            name='PDFDocument',
        ),
    ]
