# Generated by Django 5.1.4 on 2025-05-01 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0027_remove_cataloguepage_pdf_document_catalogue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='catalogues/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
