# Generated by Django 5.1.4 on 2025-05-01 05:14

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_catalogue_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/catalogues/pdf_files'), upload_to='catalogues/pdf_files/'),
        ),
    ]
