# Generated by Django 5.1.4 on 2025-05-01 05:47

import companies.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0030_remove_catalogue_pdf_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CataloguePdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Catalogue', max_length=255)),
                ('pdf_file', models.FileField(upload_to=companies.models.cat_pdf_upload_path)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CataloguePagePdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to=companies.models.cat_image_upload_path)),
                ('sellers', models.ManyToManyField(blank=True, related_name='catalogue_pagessss', to='companies.sellerprofile')),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagesss', to='companies.cataloguepdf')),
            ],
        ),
    ]
