# Generated by Django 5.1.4 on 2025-05-01 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0031_cataloguepdf_cataloguepagepdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloguepdf',
            name='companies',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='cataloguepdf',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='catalogues/covers/'),
        ),
        migrations.AddField(
            model_name='cataloguepdf',
            name='creator',
            field=models.CharField(default='Sohof', max_length=255),
        ),
        migrations.AddField(
            model_name='cataloguepdf',
            name='description',
            field=models.CharField(blank=True, default='Catalogue Description', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cataloguepdf',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cataloguepdf',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='cataloguepdf',
            name='pages',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='cataloguepdf',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cataloguepdf',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
