# Generated by Django 5.1.4 on 2025-05-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0032_cataloguepdf_companies_cataloguepdf_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cataloguepage',
            name='catalogue',
        ),
        migrations.RemoveField(
            model_name='cataloguepage',
            name='sellers',
        ),
        migrations.DeleteModel(
            name='Catalogue',
        ),
        migrations.DeleteModel(
            name='CataloguePage',
        ),
    ]
