# Generated by Django 5.1.4 on 2025-05-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_cataloguecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
