# Generated by Django 5.1.4 on 2025-05-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0038_alter_sellerprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
