# Generated by Django 5.1.4 on 2025-05-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemeta',
            name='canonical_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagemeta',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagemeta',
            name='og_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagemeta',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagemeta',
            name='og_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagemeta',
            name='robots',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagemeta',
            name='twitter_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagemeta',
            name='twitter_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagemeta',
            name='twitter_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagemeta',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
