# Generated by Django 5.1.4 on 2025-05-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatags', '0002_pagemeta_canonical_url_pagemeta_og_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemeta',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='meta/Open Graph/'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='twitter_image',
            field=models.ImageField(blank=True, null=True, upload_to='meta/twitter/'),
        ),
    ]
