# Generated by Django 5.1.4 on 2025-05-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatags', '0003_alter_pagemeta_description_alter_pagemeta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemeta',
            name='twitter_card',
            field=models.CharField(blank=True, default='summary_large_image', max_length=50, null=True),
        ),
    ]
