# Generated by Django 5.1.4 on 2025-02-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_buyerprofile_address_buyerprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
