# Generated by Django 5.1.4 on 2025-02-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_alter_buyerprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
