# Generated by Django 5.1.4 on 2025-02-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_buyerprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='buyer_profile_images/'),
        ),
    ]
