# Generated by Django 5.1.4 on 2025-05-01 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_pdfdocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFDocument',
        ),
    ]
